version: "3.9"

services:
  database:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped