version: "3.4"

services:
  database:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - database
